# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DragaoBasesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # DragaoBase. As you add validations to DragaoBase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DragaoBasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET index' do
    it 'assigns all dragao_bases as @dragao_bases' do
      dragao_base = DragaoBase.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dragao_bases)).to eq([dragao_base])
    end
  end

  describe 'GET show' do
    it 'assigns the requested dragao_base as @dragao_base' do
      dragao_base = DragaoBase.create! valid_attributes
      get :show, { id: dragao_base.to_param }, valid_session
      expect(assigns(:dragao_base)).to eq(dragao_base)
    end
  end

  describe 'GET new' do
    it 'assigns a new dragao_base as @dragao_base' do
      get :new, {}, valid_session
      expect(assigns(:dragao_base)).to a_new?(DragaoBase)
    end
  end

  describe 'GET edit' do
    it 'assigns the requested dragao_base as @dragao_base' do
      dragao_base = DragaoBase.create! valid_attributes
      get :edit, { id: dragao_base.to_param }, valid_session
      expect(assigns(:dragao_base)).to eq(dragao_base)
    end
  end

  describe 'POST create' do
    describe 'with valid params' do
      it 'creates a new DragaoBase' do
        expect do
          post :create, { dragao_base: valid_attributes }, valid_session
        end.to change(DragaoBase, :count).by(1)
      end

      it 'assigns a newly created dragao_base as @dragao_base' do
        post :create, { dragao_base: valid_attributes }, valid_session
        expect(assigns(:dragao_base)).to is_a?(DragaoBase)
        expect(assigns(:dragao_base)).to persisted?
      end

      it 'redirects to the created dragao_base' do
        post :create, { dragao_base: valid_attributes }, valid_session
        expect(response).to redirect_to(DragaoBase.last)
      end
    end

    describe 'with invalid params' do
      it 'assigns a newly created but unsaved dragao_base as @dragao_base' do
        post :create, { dragao_base: invalid_attributes }, valid_session
        expect(assigns(:dragao_base)).to a_new?(DragaoBase)
      end

      it 're-renders the "new" template' do
        post :create, { dragao_base: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested dragao_base' do
        dragao_base = DragaoBase.create! valid_attributes
        put :update, { id: dragao_base.to_param, dragao_base: new_attributes }, valid_session
        dragao_base.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested dragao_base as @dragao_base' do
        dragao_base = DragaoBase.create! valid_attributes
        put :update, { id: dragao_base.to_param, dragao_base: valid_attributes }, valid_session
        expect(assigns(:dragao_base)).to eq(dragao_base)
      end

      it 'redirects to the dragao_base' do
        dragao_base = DragaoBase.create! valid_attributes
        put :update, { id: dragao_base.to_param, dragao_base: valid_attributes }, valid_session
        expect(response).to redirect_to(dragao_base)
      end
    end

    describe 'with invalid params' do
      it 'assigns the dragao_base as @dragao_base' do
        dragao_base = DragaoBase.create! valid_attributes
        put :update, { id: dragao_base.to_param, dragao_base: invalid_attributes }, valid_session
        expect(assigns(:dragao_base)).to eq(dragao_base)
      end

      it 're-renders the "edit" template' do
        dragao_base = DragaoBase.create! valid_attributes
        put :update, { id: dragao_base.to_param, dragao_base: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE destroy' do
    it 'destroys the requested dragao_base' do
      dragao_base = DragaoBase.create! valid_attributes
      expect do
        delete :destroy, { id: dragao_base.to_param }, valid_session
      end.to change(DragaoBase, :count).by(-1)
    end

    it 'redirects to the dragao_bases list' do
      dragao_base = DragaoBase.create! valid_attributes
      delete :destroy, { id: dragao_base.to_param }, valid_session
      expect(response).to redirect_to(dragao_bases_url)
    end
  end
end
